config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
    path('users/activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

# from .views import listM
from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MateriaDetailView, MaterialUpdateView, \
    MateriaDeleteView, toggle_activiti

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', cache_page(60)(MaterialListView.as_view()), name='list'),
    path('view/<int:pk>/', MateriaDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MateriaDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activiti, name='toggle_activiti'),
    # path('list/', listM, name='list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views
from users.apps import UsersConfig
from users.views import ProfileView, RegisterView

from .views import PasswordResetView, PasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>[0-9A-Za-z]+<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', views.activate, name='activate'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

materials/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Materials(models.Model):
    name = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(verbose_name='описение')

    price = models.IntegerField(**NULLABLE, verbose_name='цена')

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    preview = models.ImageField(verbose_name='изображение', upload_to='blog/', **NULLABLE)
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='есть в наличии')

    def __str__(self):
        return f'{self.name} {self.preview}'

    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

materials/forms.py
from django import forms

from materials.models import Materials


class MaterialsForm(forms.ModelForm):
    class Meta:
        model = Materials
        fields = '__all__'
        # fields = ('title', 'body')
        # exclude = ('is_active',)

materials/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.decorators import unauthenticated_user
from materials.forms import MaterialsForm
from materials.models import Materials
from materials.services import get_cached_for_materials


class MaterialCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Materials
    form_class = MaterialsForm
    permission_required = ['materials.add_materials']
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

            # Перезатирание ключа кеша
            cache.delete('material:list')

        return super().form_valid(form)


class MaterialUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Materials
    form_class = MaterialsForm
    permission_required = ['materials.change_materials']
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.price)
            new_mat.save()

            # Перезатирание ключа кеша
            cache.delete('material:list')

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Materials

    def get_queryset(self, *args, **kwargs):
        # Использование кеша
        queryset = cache.get('material:list')

        if not queryset:
            queryset = super().get_queryset(*args, **kwargs)
            queryset = queryset.filter(is_published=True)
            # Установка кеша
            cache.set('material:list', queryset)
        return queryset


class MateriaDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Materials
    permission_required = ['materials.view_materials']

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        object.views_count = get_cached_for_materials(object.pk)
        return object

    # def get_context_data(self, **kwargs):
        # context_data = super().get_context_data(**kwargs)
        # if settings.CACHES_ENABLED:
            # key = f'subject_list{self.object.pk}'
            # subject_list = cache.get(key)
            # if subject_list is None:
                # subject_list = self.object.subject_set.all()
                # cache.set(key, subject_list)
        # else:
            # subject_list = self.object.subject_set.all()

        # context_data['subjects'] = subject_list
        # return context_data


class MateriaDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Materials
    success_url = reverse_lazy('materials:list')

    def test_func(self):
        return self.request.user.is_superuser


@login_required
@permission_required('materials.view_materials')
def toggle_activiti(request, pk):
    materials_item = get_object_or_404(Materials, pk=pk)

    if materials_item.is_active:
        materials_item.is_active = False
    else:
        materials_item.is_active = True

    materials_item.save()

    # Перезатирание ключа кеша
    cache.delete('material:list')

    return redirect(reverse('materials:list'))


# @unauthenticated_user
# def listM(request):
    # return render(request, 'materials/materials_list.html')

materials/templates/materials/materials_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_detail.html
{% extends 'catalog/base.html' %}
{% load material_mediapath %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card" style="height: 100%;">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{ object.name }}" ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body" style="padding-top: 20px; padding-left: 20px;">
                    <p>
                     Описание: {{ object.body }}
                    </p>
                </div>
                <div class="card-body" style="padding-top: 10px; padding-left: 20px;">
                    Цена:
                    {% if object.price %}
                        {{ object.price }} руб.
                    {% else %}
                        цена не указана !
                    {% endif %}
                </div>
                <div class="card-body" style="padding-top: 10px; padding-left: 20px;">
                    Просмотры: {{ object.views_count }} шт.
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card" style="height: 100%;">
                <img src="/media/{{ object.preview }}" style="max-width: 100%; height: auto; object-fit: contain;">
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 md-5">
        {% if perms.materials.add_materials %}
        <a class="btn btn-outline-primary mt-0 mb-5" href="{% url 'materials:create' %}">Добавить</a>
        {% endif %}
    </div>
    {% for obj in object_list %}
    <div class="col-md-6">
        <div class="card mb-4 box-shadow d-flex flex-column justify-content-center align-items-center text-center "
             style="width: 530px; height: 150px; overflow: auto;">
            <div class="card-body">
                <p class="card-text">
                    {{ obj|title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.materials.view_materials %}
                        <a href="{% url 'materials:view' obj.pk %}"
                           class="btn btn-cm btn-outline-secondary mr-2">Смотреть</a>
                        {% endif %}
                        {% if perms.materials.change_materials %}
                        <a href="{% url 'materials:edit' obj.pk %}" type="button"
                           class="btn btn-cm btn-outline-secondary mr-2">Редактировать</a>
                        {% endif %}
                        {% if user.is_superuser %}
                        <a href="{% url 'materials:delete' obj.pk %}" type="button"
                           class="btn btn-cm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                        {% if perms.materials.view_materials %}
                        {% if obj.is_active %}
                        <a class="btn btn-warning" href="{% url 'materials:toggle_activiti' obj.pk %}">Деактивировать</a>
                        {% else %}
                        <a class="btn btn-success" href="{% url 'materials:toggle_activiti' obj.pk %}">Активировать</a>
                        {% endif %}
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}