catalog/urls.py
from django.urls import path

from catalog import views
from catalog.apps import MainConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductDeleteView, \
    ProductUpdateView, ProductFotoView

# from .views import home

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/views/', ProductDetailView.as_view(), name='inc_products_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('product_foto/', ProductFotoView.as_view(), name='product_foto'),
    path('version/', views.product_list_activ, name='version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
    path('users/activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views
from users.apps import UsersConfig
from users.views import ProfileView, RegisterView

from .views import PasswordResetView, PasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>[0-9A-Za-z]+<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', views.activate, name='activate'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование')
    email = models.CharField(max_length=150, verbose_name='почта', unique=True, **NULLABLE)
    description = models.CharField(max_length=150, verbose_name='описание')
    image = models.ImageField(upload_to='preview/', verbose_name='изображение ', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    purchase_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='цена за килограмм', **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')

    availability = models.BooleanField(default=True, verbose_name='есть в наличии')

    def __str__(self):

        return f'{self.name} {self.description} {self.image} {self.category} {self.purchase_price}' \
               f'{self.creation_date} {self.last_modified_date} {self.availability}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('category', 'name',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    def __str__(self):
        return f'{self.title} ({self.product})'

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'


class Version(models.Model):
    name = models.CharField(max_length=150, verbose_name='наименование', **NULLABLE)
    version_number = models.IntegerField(default=0, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=False, verbose_name='признак текущей версии')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')

    def __str__(self):
        return f'{self.product} - {self.version_number} (Версия{self.version_name})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Subject, Version


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        # fields = ('name', 'description', 'email')
        # exclude = ('availability',)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if cleaned_data:
            if not cleaned_data.endswith('@') and '@' not in cleaned_data:
                raise forms.ValidationError('Должен быть введен адрес почты ')
        else:
            raise forms.ValidationError('Должен быть введен адрес почты ')
        return cleaned_data

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        exception_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                           'обман', 'полиция', 'радар')
        for word in cleaned_data.split():
            if word.lower() in exception_words:
                raise forms.ValidationError('Такое слово нельзя вводить !!!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        exception_words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                           'обман', 'полиция', 'радар')
        for word in cleaned_data.split():
            if word.lower() in exception_words:
                raise forms.ValidationError('Такое слово нельзя вводить !!!')

        return cleaned_data


class SubjectForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        # fields = ('version_number', 'version_name')
        # exclude = ('is_active',)

catalog/views.py
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from catalog.forms import ProductForm, SubjectForm, VersionForm
from catalog.models import Product, Subject, Version

from .decorators import unauthenticated_user


class ProductListView(ListView):
    model = Product


@login_required
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        print(f'{name} ({email}): {message}')

    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contacts.html', context)


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = ['catalog.add_product']
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = ['catalog.change_product']
    template_name = 'catalog/product_form_with_formset.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_success_url(self):
        return reverse('catalog:inc_products_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        SubjectFormset = inlineformset_factory(Product, Subject, form=SubjectForm, extra=1)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['subject_formset'] = SubjectFormset(self.request.POST, instance=self.object)
            context_data['version_formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['subject_formset'] = SubjectFormset(instance=self.object)
            context_data['version_formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        subject_formset = self.get_context_data()['subject_formset']
        version_formset = self.get_context_data()['version_formset']

        self.object = form.save()

        if subject_formset.is_valid() and version_formset.is_valid():
            subject_formset.instance = self.object
            subject_formset.save()

            version_formset.instance = self.object
            version_formset.save()

            # new_mat = form.save()
            # new_mat.slug = slugify(new_mat.title)
            # new_mat.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')

    def test_func(self):
        return self.request.user.is_superuser and self.request.user.is_staff


# class ProductFotoView(View):
    # def get(self, request):
        # Получение списка файлов из папки media/preview
        # foto_dir = 'media/preview'  # Путь к папке с фотографиями
        # foto_list = os.listdir(foto_dir)  # Список всех файлов в папке

        # Создание списка URL-адресов для каждой фотографии
        # foto_urls = []
        # for foto_file in foto_list:
            # foto_path = os.path.join(foto_dir, foto_file)
            # Формируем URL, добавляя путь относительно корневой директории проекта
            # foto_url = request.build_absolute_uri(f'/{foto_path}')
            # foto_urls.append(foto_url)

        # Передача списка URL-адресов в шаблон
        # context = {'foto_urls': foto_urls}

        # return render(request, 'catalog/product_foto.html', context)


class ProductFotoView(View):
    def get(self, request):
        context = {
            'products': Product.objects.exclude(image__isnull=True)
        }
        return render(request, 'catalog/product_foto.html', context)


@login_required
def product_list_activ(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'catalog/product_is_active.html', context)


@unauthenticated_user
def home(request):
    return render(request, 'catalog/base.html')

catalog/templates/catalog/base.html
{% load static %}

    <html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{{ title }}</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'css/album.css' %}" rel="stylesheet">
    </head>

    <body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                    </div>
                        {% include 'catalog/includes/inc_catalog_menu.html' %}
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark box-shadow">
            <div class="container d-flex justify-content-between">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="mr-2">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                        <circle cx="12" cy="13" r="4"></circle>
                    </svg>
                    <div>
                        {% include 'catalog/product_foto.html' %}
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                        aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">{{ title }}</h1>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row">
                        {% block content %}
                        {% endblock %}
                </div>
            </div>
        </div>
    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>&copy; 2023 - {% now 'Y' %}</p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    </body>
    </html>
    >>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Офис МСК<br>
                Офис СПБ
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2>Напишите нам</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name"/>
                <input class="form-control mb-2" name="email"/>
                <textarea class="form-control mb-2" name="message"></textarea>
                <button type="submit" class="btn btn-primary form-control">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12 md-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    <div class="card-body" style="padding-top: 10px; padding-left: 20px;">
    </div>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {% if object.availability %}
                {{ object.name|title }}
                {% else %}
                <span class="text-muted">{{ object.name|title }}</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:inc_products_detail' pk=object.pk %}">Смотреть</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}

{% block content %}
<div class="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о продукте
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Наименование</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{ object.description }}</td>
                        </tr>
                        <tr>
                            <td>Категория</td>
                            <td>{{ object.category }}</td>
                        </tr>
                        <tr>
                            <td>Цена за килограмм</td>
                            <td>{{ object.purchase_price }}</td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td>{{ object.creation_date }}</td>
                        </tr>
                        <tr>
                            <td>Дата последнего изменения</td>
                            <td>{{ object.last_modified_date }}</td>
                        </tr>
                        <tr>
                            <td>Активный товар</td>
                            <td>
                                {% if object.is_active %}
                                    Нет
                                {% else %}
                                    Да
                                {% endif %}
                            </td>
                        </tr>
                    </table>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>

        <div class="col-6">
            <div class="card" style="height: 100%;">
                <img src="/media/{{ object.image }}" style="max-width: 100%; height: auto; object-fit: contain;">
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primari" style="background-color: blue;
                         color: white;">Создать
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card h-100">
                <div class="card-header bg-primary text-white">
                    Форма
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary" style="background-color: blue; color: white;">
                        Создать
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card h-100">
                <div class="card-header bg-primary text-white">
                    Предметы
                </div>
                <div class="card-body">
                    {{ subject_formset.management_form }}
                    {% for form in subject_formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

            <div class="col-6">
                <div class="card h-100">
                    <div class="card-header bg-primary text-white">
                        Версии
                    </div>
                    <div class="card-body">
                        {{ version_formset.management_form }}
                        {% for form in version_formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>

    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_foto.html
{% load mediapath %}

<div>
    <div class="col-sm-4 offset-md-1 py-4">
        <div>
            {% for product in products %}
                <img src="{{ product.image|mediapath }}" width="300" height="300" alt="">
            {% endfor %}
        </div>
    </div>
</div>

catalog/templates/catalog/product_is_active.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                Активные товары
            </h3>
            <ul>
                {% for product in products %}
                    <ul>&nbsp;</ul>
                    <h5>{{ product.name }}</h5>

                    {% if object.is_active %}
                        <li>Активная версия: {{ object.version_name }}</li>
                        <li>Номер версии: {{ object.version_number }}</li>
                        <li>Статус активности: {{ object.is_active }}</li>
                        <li>Наличие: {{ object.availability }}</li>
                    {% else %}
                        <li>Не активная версия</li>
                    {% endif %}

                {% empty %}
                        <li>Нет товаров.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12 md-5">
    {% if perms.catalog.add_product %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    {% endif %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:version' %}">Список продуктов</a>
    <div class="card-body" style="padding-top: 10px; padding-left: 20px;">
    </div>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {% if object.availability %}
                {{ object.name|title }}
                {% else %}
                <span class="text-muted">{{ object.name|title }}</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:inc_products_detail' pk=object.pk %}" class="btn mr-2">Смотреть</a>
                    {% if perms.catalog.change_product %}
                    <a href="{% url 'catalog:update' object.pk %}" class="btn" style="color: red;">Редактировать</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'catalog:delete' object.pk %}" class="btn" style="color: red;">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}